# MEASURING HATE SPEECH

## 1. Introduzione

## 2. Setup & EDA

### 2.1. - Importazione librerie e setup generale


Oltre agli import fondamentali, vengono inizializzate le costanti che saranno utili per l'importazione del dataset e per l'Explorative Data Analysis.

In [ ]:
import sys
import subprocess
from pathlib import Path
from datasets import load_dataset
import pandas as pd
from src.data import (
    get_column_groups,
    summarize_dataset,
    HF_DATASET_NAME,
    HF_CONFIG,
)

,comment_id,annotator_id,platform,sentiment,respect,insult,humiliate,status,dehumanize,violence,...,annotator_religion_hindu,annotator_religion_jewish,annotator_religion_mormon,annotator_religion_muslim,annotator_religion_nothing,annotator_religion_other,annotator_sexuality_bisexual,annotator_sexuality_gay,annotator_sexuality_straight,annotator_sexuality_other
0,47777,10873,3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,39773,2790,2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
2,47101,3379,3,4.0,4.0,4.0,4.0,4.0,4.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,43625,7365,3,2.0,3.0,2.0,1.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
4,12538,488,0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,False,False,False,False,False,False,False,False,True,False
5,11001,527,0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False
6,13168,3275,0,4.0,4.0,4.0,4.0,3.0,3.0,0.0,...,False,False,False,False,False,False,False,False,True,False
7,17034,6801,0,4.0,4.0,4.0,4.0,4.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
8,40171,10363,3,4.0,4.0,4.0,3.0,3.0,3.0,0.0,...,False,False,False,False,False,False,False,False,True,False
9,1006,10615,0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,False,False,False,False,False,False,False,False,True,False
10,23643,9750,2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
11,14241,7331,0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,...,False,False,False,False,False,False,False,False,True,False
12,20583,7259,2,4.0,2.0,1.0,2.0,2.0,3.0,0.0,...,False,False,False,False,False,True,False,False,True,False
13,30879,1329,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,False,False,False,False,False,False,False,False,True,False
14,29527,2171,2,3.0,3.0,3.0,3.0,4.0,3.0,0.0,...,False,False,False,False,True,False,False,False,True,False

### 2.2. Caricamento del dataset

Caricamento del dataset come DataFrame e creazione di una copia da mantenersi RAW.

In [ ]:
df: pd.DataFrame = load_dataset(HF_DATASET_NAME, HF_CONFIG)['train'].to_pandas()
df_raw: pd.DataFrame = df.copy()

df.head(15)

,comment_id,annotator_id,platform,sentiment,respect,insult,humiliate,status,dehumanize,violence,...,annotator_religion_hindu,annotator_religion_jewish,annotator_religion_mormon,annotator_religion_muslim,annotator_religion_nothing,annotator_religion_other,annotator_sexuality_bisexual,annotator_sexuality_gay,annotator_sexuality_straight,annotator_sexuality_other
0,47777,10873,3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,39773,2790,2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
2,47101,3379,3,4.0,4.0,4.0,4.0,4.0,4.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,43625,7365,3,2.0,3.0,2.0,1.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
4,12538,488,0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,False,False,False,False,False,False,False,False,True,False
5,11001,527,0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False
6,13168,3275,0,4.0,4.0,4.0,4.0,3.0,3.0,0.0,...,False,False,False,False,False,False,False,False,True,False
7,17034,6801,0,4.0,4.0,4.0,4.0,4.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
8,40171,10363,3,4.0,4.0,4.0,3.0,3.0,3.0,0.0,...,False,False,False,False,False,False,False,False,True,False
9,1006,10615,0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,False,False,False,False,False,False,False,False,True,False
10,23643,9750,2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
11,14241,7331,0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,...,False,False,False,False,False,False,False,False,True,False
12,20583,7259,2,4.0,2.0,1.0,2.0,2.0,3.0,0.0,...,False,False,False,False,False,True,False,False,True,False
13,30879,1329,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,False,False,False,False,False,False,False,False,True,False
14,29527,2171,2,3.0,3.0,3.0,3.0,4.0,3.0,0.0,...,False,False,False,False,True,False,False,False,True,False

#

## 3. - Fairness

## 4. - Privacy

## 5. - Implementazione di un modello spiegabile